add protobuf and some serilizing functions
CovenantSQL/CovenantSQL pull request #24
Opened 2018-05-25 06:30 UTC by zeqing-guo

2018-05-25 06:35 UTC, leventeliu approved these changes
LGTM, approve.

2018-05-25 06:36 UTC, thunderdatabase commented on sqlchain/tx.go
> +type TX struct {
**[golint]** <sub>reported by [reviewdog](https://github.com/haya14busa/reviewdog) :dog:</sub>
exported type TX should have comment or be unexported

2018-05-25 06:36 UTC, thunderdatabase commented on sqlchain/tx.go
> +type TxIn struct {
**[golint]** <sub>reported by [reviewdog](https://github.com/haya14busa/reviewdog) :dog:</sub>
exported type TxIn should have comment or be unexported

2018-05-25 06:36 UTC, thunderdatabase commented on sqlchain/tx.go
> +type TxOut struct {
**[golint]** <sub>reported by [reviewdog](https://github.com/haya14busa/reviewdog) :dog:</sub>
exported type TxOut should have comment or be unexported

2018-05-25 06:39 UTC, xq262144 requested changes
commit comment typo

2018-05-28 15:29 UTC, xq262144 approved these changes

2018-05-29 07:33 UTC, merged