Simplify cql config and use IPv6 for bootstrap
CovenantSQL/CovenantSQL pull request #290
Opened 2019-03-26 09:46 UTC by auxten

2019-03-26 12:30 UTC, covenantdb commented on client/driver.go
> +	// Default path of config file
**[golint]** <sub>reported by [reviewdog](https://github.com/haya14busa/reviewdog) :dog:</sub>
comment on exported var DefaultConfigFile should be of the form "DefaultConfigFile ..."

2019-03-26 12:30 UTC, covenantdb commented on route/ipv6seed.go
> +	NODEID = "id."
**[golint]** <sub>reported by [reviewdog](https://github.com/haya14busa/reviewdog) :dog:</sub>
exported const NODEID should have comment (or a comment on this block) or be unexported

2019-03-26 12:30 UTC, covenantdb commented on route/ipv6seed.go
> +type IPv6SeedClient struct{}
**[golint]** <sub>reported by [reviewdog](https://github.com/haya14busa/reviewdog) :dog:</sub>
exported type IPv6SeedClient should have comment or be unexported

2019-03-26 12:30 UTC, covenantdb commented on route/ipv6seed.go
> +func (isc *IPv6SeedClient) GetBPFromDNSSeed(BPDomain string) (BPNodes IDNodeMap, err error) {
**[golint]** <sub>reported by [reviewdog](https://github.com/haya14busa/reviewdog) :dog:</sub>
exported method IPv6SeedClient.GetBPFromDNSSeed should have comment or be unexported

2019-03-26 12:30 UTC, covenantdb commented on route/ipv6seed.go
> +	nodeIdBuf, err := ipv6.FromDomain(NODEID + BPDomain)
**[golint]** <sub>reported by [reviewdog](https://github.com/haya14busa/reviewdog) :dog:</sub>
var nodeIdBuf should be nodeIDBuf

2019-03-26 12:30 UTC, covenantdb commented on route/ipv6seed.go
> +	var nodeId proto.RawNodeID
**[golint]** <sub>reported by [reviewdog](https://github.com/haya14busa/reviewdog) :dog:</sub>
var nodeId should be nodeID

2019-03-26 12:30 UTC, covenantdb commented on route/ipv6seed.go
> +func (isc *IPv6SeedClient) GenBPIPv6(node *proto.Node, domain string) (out string, err error) {
**[golint]** <sub>reported by [reviewdog](https://github.com/haya14busa/reviewdog) :dog:</sub>
exported method IPv6SeedClient.GenBPIPv6 should have comment or be unexported

2019-03-26 12:30 UTC, covenantdb commented on route/ipv6seed.go
> +	nodeIdIps, err := ipv6.ToIPv6(node.ID.ToRawNodeID().AsBytes())
**[golint]** <sub>reported by [reviewdog](https://github.com/haya14busa/reviewdog) :dog:</sub>
var nodeIdIps should be nodeIDIps

2019-03-27 02:15 UTC, laodouya requested changes

2019-03-27 02:15 UTC, laodouya commented on cmd/cql-utils/confgen.go
> +	testnetConfig.KnownNodes[0] = proto.Node{
If KnownNodes is not nil, this will erase first exist node.

2019-03-27 02:24 UTC, auxten commented on cmd/cql-utils/confgen.go
> +	testnetConfig.KnownNodes[0] = proto.Node{
Fixed

2019-03-27 02:25 UTC, laodouya approved these changes

2019-03-27 02:42 UTC, leventeliu approved these changes
LGTM.

2019-03-27 02:42 UTC, merged